name: "AI Code Reviewer"
description: "Educational AI code reviewer with RAG context"

inputs:
  huggingface_token:
    description: "HuggingFace API Token"
    required: true
  github_token:
    description: "GitHub Personal Access Token"
    required: true
  enable_rag:
    description: "Enable RAG (Retrieval-Augmented Generation) context for code review"
    required: false
    default: "false"
  rag_db_path:
    description: "Path to ChromaDB database for RAG"
    required: false
    default: "./chroma_db"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: pip install -q -r ${{ github.action_path }}/requirements.txt

    - name: Build RAG Database
      if: inputs.enable_rag == 'true'
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        RAG_DB_PATH: ${{ inputs.rag_db_path }}
      run: |
        echo "📚 Building RAG database..."
        python ${{ github.action_path }}/build_rag.py

    - name: Run reviewer
      shell: bash
      env:
        HUGGINGFACE_TOKEN: ${{ inputs.huggingface_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ENABLE_RAG: ${{ inputs.enable_rag }}
        RAG_DB_PATH: ${{ inputs.rag_db_path }}
      run: python ${{ github.action_path }}/reviewer.py
