name: 'AI Code Reviewer'
description: 'Educational AI code reviewer'

inputs:
  huggingface_token:
    description: 'HuggingFace API Token'
    required: true
  github_token:
    description: 'GitHub Personal Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: pip install -q -r ${{ github.action_path }}/requirements.txt
    
    - name: Run reviewer
      shell: bash
      env:
        HUGGINGFACE_TOKEN: ${{ inputs.huggingface_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: python ${{ github.action_path }}/reviewer.py
